name: pkgcheck

on:
  workflow_run:
    workflows: ["R-CMD-check"]
    types: [completed]
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
        with:
          post-to-issue: ${{ github.event_name != 'pull_request' }}
          summary-only: true
          append-to-issue: true
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}
